### ISSUE TITLE
Fixed DNS closes the app

### ISSUE THREAD

**Issue by nachol** [BornToBeRoot/NETworkManager#162]
**Describe your issue or feature request**:
While setting a fixed DNS setting in an interfaces the app closes without any error or log. The application is being run as admin.

**Steps to reproduce the issue**:

1. Network Interface
2. Configure
3. Set up "Use the following DNS server addresses"
4. Apply

**NETworkManager version**:
1.8.2.0

**Windows version**:
Windows 10 Pro Version 1809 Build 17763.107

**.NET-Framework version**:
4.7.03190

**Screenshots**
![imagen](https://user-images.githubusercontent.com/2257462/50448366-9621f000-08ff-11e9-8b8e-d249ee032e91.png)

**Comment by BornToBeRoot** [comment]
Can you post the stacktrace from the event viewer?

(eventvwr.msc / Application)

Have you set a dynamic (dhcp) or static ip address ?

**Comment by nachol** [comment]
The IP is set to dynamic. Only the DNS is specified.

In the event log there are 2 erros:

![imagen](https://user-images.githubusercontent.com/2257462/50452769-dc387d00-091a-11e9-88df-e2f18c2c177d.png)

**.Net Runtime:**
`Application: NETworkManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotImplementedException
   at NETworkManager.ViewModels.NetworkInterfaceViewModel.<get_ApplyNetworkInterfaceConfigCommand>b__176_0(System.Object)
   at NETworkManager.Utilities.RelayCommand.Execute(System.Object)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at NETworkManager.App.Main()
`

**Application Error:**
`Faulting application name: NETworkManager.exe, version: 1.8.2.0, time stamp: 0x5c100f35
Faulting module name: KERNELBASE.dll, version: 10.0.17763.1, time stamp: 0x30bd5043
Exception code: 0xe0434352
Fault offset: 0x0011aaf2
Faulting process id: 0x20ec
Faulting application start time: 0x01d49d407df17497
Faulting application path: C:\Program Files (x86)\NETworkManager\NETworkManager.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 9fc2d88d-7397-4d83-953b-8d552a691f0d
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by BornToBeRoot** [comment]
Fix will be in the next release! Thanks!

**Comment by nachol** [comment]
Appreciated! Great application!
