### ISSUE TITLE
Ping and Ping Monitor: SocketException: No such host is known

### ISSUE THREAD

**Issue by PCAssistSoftware** [BornToBeRoot/NETworkManager#232]
This occurs on both Ping and Ping Monitor

Simply entering an IP on my local network - 192.168.1.100 and clicking button to start Pinging

About 5 packets get sent okay and then get error below:-

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NETworkManager.Models.Network.Ping.<>c__DisplayClass23_1.<SendAsync>b__1() in C:\Users\darre\Downloads\networkmanager\NETworkManager-master\Source\NETworkManager\Models\Network\Ping.cs:line 66
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

  This exception was originally thrown at this call stack:
	System.Net.Dns.HostResolutionEndHelper(System.IAsyncResult)
	System.Net.Dns.EndGetHostEntry(System.IAsyncResult)

Inner Exception 1:
SocketException: No such host is known

![image](https://user-images.githubusercontent.com/10872799/71532172-0a63ea80-28ea-11ea-8b16-a08a04316599.png)

**Comment by PCAssistSoftware** [comment]
If I click Continue in the debugger it then continues okay and keeps going without error

**Comment by BornToBeRoot** [comment]
Yep. Thats why there is a try-catch... if the hostname cannot be resolved (SocketException) it will continue... 

It also runs in a separat thread... as soon as the hostname is resolved... it will show up in the result.

**Comment by PCAssistSoftware** [comment]
okay nice one, thanks
