### ISSUE TITLE
Dragged out tab - App crash if dialog coordinator is not available

### ISSUE THREAD

**Issue by BornToBeRoot** [BornToBeRoot/NETworkManager#2516]
Add profile from ip scanner  context menu...

<details>
2023-10-05 15:17:02,774 [1] FATAL NETworkManager.App - Unhandled exception occured!
2023-10-05 15:17:02,815 [1] FATAL NETworkManager.App - Exception raised by: System.InvalidOperationException: Context is not inside a MetroWindow.
   at MahApps.Metro.Controls.Dialogs.DialogCoordinator.GetMetroWindow(Object context)
   at MahApps.Metro.Controls.Dialogs.DialogCoordinator.ShowMetroDialogAsync(Object context, BaseMetroDialog dialog, MetroDialogSettings settings)
   at NETworkManager.ProfileDialogManager.ShowAddProfileDialog(IProfileManagerMinimal viewModel, IDialogCoordinator dialogCoordinator, ProfileInfo profile, String group, ApplicationName applicationName)
   at NETworkManager.ViewModels.IPScannerViewModel.AddProfileSelectedHostAction()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at NETworkManager.App.Main()
</details>

**Comment by BornToBeRoot** [comment]
https://github.com/MahApps/MahApps.Metro/issues/4424

**Comment by BornToBeRoot** [comment]
Possible workaround: https://github.com/MahApps/MahApps.Metro/issues/4424#issuecomment-2021329962
