### ISSUE TITLE
Right CLick NETworkManager Tray icon Issue

### ISSUE THREAD

**Issue by Galthariel** [BornToBeRoot/NETworkManager#2614]
**Describe your issue**:

**Steps to reproduce the issue**:

1. Go to Options, Window, and pick Always show icon in Tray
2. Right Click Icon in Tray

NETworkManager version: Portable v2024.1.6.0 (Latest)

Windows version 11 22H2 Build: 22621.2861

NET version 8.0

**Screenshots**

![2024-01-07_11-07-16](https://github.com/BornToBeRoot/NETworkManager/assets/51491805/da4fbe38-b582-45c5-8197-4680dabad78c)

<details>
************** Exception Text **************
System.Windows.ResourceReferenceKeyNotFoundException: 'ContextMenuNotifyIcon' resource not found.
   at MS.Internal.Helper.FindResourceHelper.DoTryCatchWhen(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at MS.Internal.Helper.FindResourceHelper.TryCatchWhen()
   at System.Windows.FrameworkElement.FindResource(Object resourceKey)
   at NETworkManager.MainWindow.NotifyIcon_MouseDown(Object sender, MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

</details>
Error doesn't happen with the previous version 2023.11.28.0

**Comment by BornToBeRoot** [comment]
@Galthariel thx. I fixed it in #2615

I create a new release.
