### ISSUE TITLE
Crash by clicking on the WiFi Button, if no WiFi adapter found

### ISSUE THREAD

**Issue by r2x-ch** [BornToBeRoot/NETworkManager#267]
**Describe your issue**: NETworkManager crashes by clicking on the WiFi Button, if no WiFi adapter found

**NETworkManager version**: 2020.1

**Windows version**: Windows Server 2019

**.NET-Framework version**: v4.0.30319

<details>
<summary>
Application: NETworkManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr)
   at Windows.Devices.WiFi.WiFiAdapter.FindAllAdaptersAsync()
   at NETworkManager.Models.Network.WiFi+<GetAdapterAsync>d__0.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NETworkManager.ViewModels.WiFiViewModel+<LoadAdapters>d__83.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at NETworkManager.App.Main()
</summary>

</details>

**Comment by BornToBeRoot** [comment]
Thanks for reporting. If no wifi adapter is available... there should be a note and a "refresh" button.

I will take a look at this.

**Comment by BornToBeRoot** [comment]
Looks like Server 2019 doesn't support https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts

I will catch this error in the next release and display a message that wifi is not supported on Server 2019.
![image](https://user-images.githubusercontent.com/16019165/73486969-61a42180-43a6-11ea-9d51-baf45bb2bb94.png)

**Comment by BornToBeRoot** [comment]
Fix is in the next release!
