### ISSUE TITLE
NETwork manager crashes after splash screen

### ISSUE THREAD

**Issue by Pentagrade** [BornToBeRoot/NETworkManager#270]
**Describe your issue**: NETwork Manager crashes on launch silently. Shows the splash picture then nothing.

**Steps to reproduce the issue**:

1. Install latest version of NETwork Manager
2. Launch the program
3. Nothing opens

(I have tried the portable version, this issue doesn't affect it, only the installable copy. I have tried reinstalling too)

**NETworkManager version**: 2020.1.0

**Windows version**: WIndows 10 Pro 64bit 1909

**.NET-Framework version**: 4.8

**Screenshots** N/A

```
Application: NETworkManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

```

**Comment by BornToBeRoot** [comment]
Can you backup (copy) this folders and then delete them:

`%AppData%\NETworkManager`
`%LocalAppData%\NETworkManager`

Then try again. Maybe there are some files from version 1.x


EDIT: Is there more in the EventLog?

**Comment by BornToBeRoot** [comment]
I could reproduce this issue. It looks like your profile file is broken.

**Comment by Pentagrade** [comment]
@BornToBeRoot Sorry for not responding sooner, the fix provided has worked, thanks for your help :)

**Comment by BornToBeRoot** [comment]
Thanks! I reopen the issue... i want to display a messagebox/dialog if this happens again...

The application should not just crash 😄

**Comment by Pentagrade** [comment]
Ah of course :D

**Comment by BornToBeRoot** [comment]
![image](https://user-images.githubusercontent.com/16019165/107131919-33232580-68db-11eb-8086-c9c86a8d2663.png)
