### ISSUE TITLE
Subnet calculator crashing 

### ISSUE THREAD

**Issue by jeff-fan** [BornToBeRoot/NETworkManager#319]
**Describe your issue**:
When Calculating subnets using subnetmask the application crashes 

**Steps to reproduce the issue**:

1. Subnet Calculator
2. Subnetting
3. Subnet: 10.0.0.0/8
    New subnetmask or CIDR: 255.255.0.0
4. Click Calculate

**NETworkManager version**: 
2020.5.1

**Windows version**:
Win 10 1903

**.NET-Framework version**:
4.8

**Screenshots**
![image](https://user-images.githubusercontent.com/10235330/90565688-8b673f00-e164-11ea-98b1-2f27f998edc5.png)

<details>
<summary>
Application: NETworkManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Net.IPNetwork.InternalSubnet(Boolean, System.Net.IPNetwork, Byte, System.Net.IPNetworkCollection ByRef)
   at NETworkManager.ViewModels.SubnetCalculatorSubnettingViewModel+<>c__DisplayClass78_0.<Calculate>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NETworkManager.ViewModels.SubnetCalculatorSubnettingViewModel+<Calculate>d__78.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at NETworkManager.App.Main()
</summary>
</details>

**Comment by BornToBeRoot** [comment]
Thanks for the report. It seems to work with:

10.0.0.0/8
/16


I try to fix it for the next release.

**Comment by BornToBeRoot** [comment]
Fix 1
![image](https://user-images.githubusercontent.com/16019165/90686473-a7a1d380-e26b-11ea-9fdf-ad9829bc73e2.png)

Fix 2
![image](https://user-images.githubusercontent.com/16019165/90686481-abcdf100-e26b-11ea-8e6e-a6bca1a0a551.png)

Fix is in the netcore-3.1 branch and will be released with the next update :)

**Comment by BornToBeRoot** [comment]
Fix: https://github.com/BornToBeRoot/NETworkManager/releases/tag/2020.9.0
