### ISSUE TITLE
.NET5.0 - LLDP/CDP capture doesn't work

### ISSUE THREAD

**Issue by BornToBeRoot** [BornToBeRoot/NETworkManager#326]
Script not executed?!

**Comment by BornToBeRoot** [comment]
StackTrace... 

```
System.InvalidProgramException
  HResult=0x8013153A
  Message=Common Language Runtime detected an invalid program.
  Source=System.Management.Automation
  StackTrace:
   at System.Management.Automation.PowerShell.Create()
   at NETworkManager.Models.Network.DiscoveryProtocol.<>c__DisplayClass18_0.<CaptureAsync>b__0() in D:\GitHub_Repositories\NETworkManager\Source\NETworkManager.Models\Network\DiscoveryProtocol.cs:line 100
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```
