### ISSUE TITLE
[Please vote] Improve UI / reduce tab size

### ISSUE THREAD

**Issue by MostHated** [BornToBeRoot/NETworkManager#398]
Hello,
    First, I wanted to say thanks for the great tool, nice to have so many tools all in one place. That said, I would like to request the ability to decrease the size of the top bar, specifically when doing RDP, as I feel that it is an awful lot of screen real-estate (at least an inch, or inch and a half?) being lost off the top because of the tabs. Perhaps similar to Firefox, where the tabs are actually part of the title bar? (if possible, of course) I would be more than happy just to be able to shrink down the tab sizes or something. Anything, lol. 

Thanks,
-MH

**Comment by BornToBeRoot** [comment]
Hi,

thank for your feedback!

It's currently not possible to move the tabs to the title bar. 
I also think the tabs are a little too big. I will see what i can do to improved the UI. 

I need to adjust the menu and profiles view. Profiles should be easy to resize. The menu could be a bit tricky.

![image](https://user-images.githubusercontent.com/16019165/102118044-72834780-3e3f-11eb-9946-4a44f8ca784d.png)

**Comment by BornToBeRoot** [comment]
If i reduce the tab size like this, the maximum i get would be about 10-12px. I think everything else would be to small (icon, text)

![image](https://user-images.githubusercontent.com/16019165/102702570-9641f580-4264-11eb-9072-241e74db6c1c.png)

**Comment by BornToBeRoot** [comment]
The gui now looks like this. Maybe up-/downvote this to give me some feedback, bevore i implement it everywhere.

PR #412 

![image](https://user-images.githubusercontent.com/16019165/102703041-32223000-426a-11eb-8057-cd2b927f0753.png)

![image](https://user-images.githubusercontent.com/16019165/102703054-6269ce80-426a-11eb-87a1-603a1b57e152.png)

![image](https://user-images.githubusercontent.com/16019165/102703098-02bff300-426b-11eb-9c3c-cf404ab235fd.png)

**Comment by MostHated** [comment]
I want to say that it looks better, but it's hard to be sure just how much without seeing it how I would use it. The place I was hoping for more space was in a remote desktop session. TBH, though, even if it is just a little bit, any extra room is much better than none. 👍

**Comment by BornToBeRoot** [comment]
I reduced the tab size and reworked the UI a bit. You can check it out:

URL: https://cloud.borntoberoot.net/s/8H8kC9EzYCsEQGL
PW: `2020Issue#398`

Or wait for the next release ;)

**Comment by MostHated** [comment]
#### Edit - It looks like that was the problem. The folder had a pound symbol (#) in it and it didn't seem to take kindly to that. Once I removed that, it fired up.
---
Unfortunately, it looks like there was a bit of an issue with the build.

These occur immediately upon attempting to launch the executable, resulting in the appearance of nothing happening at all when opening it.
Checking through some of the logs, I am seeing the following:

<details>
<summary>.Net Runtime</summary>

```
Application: NETworkManager.exe
CoreCLR Version: 5.0.120.57516
.NET Version: 5.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: Set property 'System.Windows.ResourceDictionary.Source' threw an exception.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\mosthated\Downloads\Resources\Styles\WindowStyles.xaml'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at MS.Internal.AppModel.ContentFilePart.GetStreamCore(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at MS.Internal.IO.Packaging.PackagePartExtensions.GetSeekableStream(PackagePart packPart, FileMode mode, FileAccess access)
   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at MS.Internal.WpfWebRequestHelper.GetContentType(WebResponse response)
   at MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType& contentType)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_Source>b__342_0(Object target, Object value)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at NETworkManager.App.InitializeComponent()
   at NETworkManager.App.Main()
```
</details>

<details>
<summary>Application Error</summary>

Faulting application name: NETworkManager.exe, version: 2020.12.1.0, time stamp: 0x5fbf100e
Faulting module name: KERNELBASE.dll, version: 10.0.19041.207, time stamp: 0x746c1866
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0xc004
Faulting application start time: 0x01d6dcce9faa9d5a
Faulting application path: C:\Users\mosthated\Downloads\NETworkManager_2020.12.1_Portable_ISSUE#398\NETworkManager\NETworkManager.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 285ec70a-32c6-44b3-b6c9-e743b9d24fc0
Faulting package full name: 
Faulting package-relative application ID: 

</details>

It looks like it is not properly taking into account the folder in which it is actually in. Though, perhaps it has to do with the characters in the folder name. Let me sanitize the folder name a bit and try again.

![](https://i.imgur.com/1KbyT7Y.png)

**Comment by BornToBeRoot** [comment]
Mhh. Good to know. So i won't use `# ` in the future ^^
