### ISSUE TITLE
Lastest Version 2020.12.2.0 Fails to open faults on startup

### ISSUE THREAD

**Issue by ghost-sage** [BornToBeRoot/NETworkManager#435]
**Describe your issue**:
Lastest Version 2020.12.2.0 Fails to open when trying to start app Event viewer shows multiple issues one is with the Kernalbase. dll faulting' 
**Steps to reproduce the issue**:

1. Click open
2.
3.

**NETworkManager version**: 

**Windows version**:
Microsoft Windows 10 Pro 64-bit (1909, 18363.1256)
**.NET-Framework version**:
5.0.1
**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>
Application Error:
Faulting application name: NETworkManager.exe, version: 2020.12.2.0, time stamp: 0x5fbf100e
Faulting module name: KERNELBASE.dll, version: 10.0.18362.1237, time stamp: 0x71e81044
Exception code: 0xe0434352
Fault offset: 0x0000000000043b29
Faulting process id: 0x924c
Faulting application start time: 0x01d6e45a15913892
Faulting application path: C:\Program Files (x86)\NETworkManager\NETworkManager.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 33deb3ca-1d76-44c4-b980-ce6e533948ee
Faulting package full name: 
Faulting package-relative application ID: 

.NETRuntime Error:
Application: NETworkManager.exe
CoreCLR Version: 5.0.120.57516
.NET Version: 5.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'NETworkManager.MainWindow' that matches the specified binding constraints threw an exception.
 ---> System.IO.IOException: Cannot locate resource 'resources/images/networkmanager.ico'.
   at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at MS.Internal.IO.Packaging.PackagePartExtensions.GetSeekableStream(PackagePart packPart, FileMode mode, FileAccess access)
   at MS.Internal.IO.Packaging.PackagePartExtensions.GetSeekableStream(PackagePart packPart)
   at System.Windows.Application.GetResourceStream(Uri uriResource)
   at NETworkManager.MainWindow.InitNotifyIcon()
   at NETworkManager.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at NETworkManager.App.Main()

</details>

**Comment by BornToBeRoot** [comment]
Hi,

the TrayIcon seems to be broken 😢 

I will fix it with the next release.

Workaround: 
Edit the file `C:\Users\USERNAME\AppData\Roaming\NETworkManager\Settings\Settings.xml` 
or in the Portable-Version `APPFOLDER\Settings\Settings.xml`

Change the value of the setting from `true` to `false`:
<TrayIcon_AlwaysShowIcon>false</TrayIcon_AlwaysShowIcon>


Greetings


Edit:
You should disable the option "Minimize to Tray instead of taskbar" in Settings\Window until an update is available.

**Comment by ghost-sage** [comment]
Hi,

That did the trick everything is now working.

Best Regards,

Gabrail C. Meishaide

Mobile: 513.344.6980
VOIP: 513-407-9336
Email: gmeishaide@gmail.com
Linkedin Profile: http://www.linkedin.com/pub/gabrail-meishaide/5/808/555/

Confidentiality Notice - This correspondence and accompanying documents may contain confidential information belonging to the sender which is legally privileged. The information is intended only for the use of the individual(s) or entity named above. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this communication in error, please notify us immediately to arrange for the return of these documents.

Sent using Outlook<https://aka.ms/sdimjr> for iOS

________________________________
