### ISSUE TITLE
Crash in Remote Desktop

### ISSUE THREAD

**Issue by pboulton** [BornToBeRoot/NETworkManager#767]
**Describe your issue**:

**Steps to reproduce the issue**:

1.IP Scanner to scan Lan
2.Right click on a Windows 10 computer on the LAN
3.Select 'Remote Desktop'
4.Any permutation of input selection causes crash (complete application termination with no .Net crash messages etc..)

**NETworkManager version**: 2021.3.28.0

**Windows version**: Windows 10 Pro, 64 bit, running in a VM (but also happens from host of same type)

**.NET-Framework version**: windowsdesktop-runtime-5.0.5-win-x64.exe

**Screenshots**

<details>
<summary>Eventlog 
Application: NETworkManager.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at NETworkManager.Models.RemoteDesktopTMP.RemoteDesktop.CreateSessionInfo(ProfileInfo profileInfo)
   at NETworkManager.ViewModels.RemoteDesktopHostViewModel.<>c__DisplayClass91_0.<<Connect>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at NETworkManager.App.Main()

... and ...

Faulting application name: NETworkManager.exe, version: 2021.3.28.0, time stamp: 0x602c44b3
Faulting module name: KERNELBASE.dll, version: 10.0.18362.959, time stamp: 0x7b90c1b5
Exception code: 0xe0434352
Fault offset: 0x000000000003a799
Faulting process id: 0x12d8
Faulting application start time: 0x01d73771bf651a4c
Faulting application path: C:\Users\Peter Boulton\Desktop\NETworkManager\NETworkManager.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 76717ea7-8968-41d6-b09a-85dbeffa945f
Faulting package full name: 
Faulting package-relative application ID: 

</summary>

</details>

**Comment by BornToBeRoot** [comment]
Thanks! Will be fixed in the next release.

**Comment by pboulton** [comment]
Triiffic!  Thank you.  (Really useful and nicely designed piece of software! 👍)
